#!/bin/bash
# Opt-in: installs the hooks that keep the cursor color following the active
# Omarchy theme automatically. Run this yourself; nothing in this plugin does
# it on install (see README.md).
#
# Two hooks, one generated script:
#   theme-set   recolor on every `omarchy theme set`
#   post-boot   re-apply once per login. `hyprctl setcursor` only lasts for
#               the running compositor, and Omarchy sets no HYPRCURSOR_THEME,
#               so at startup hyprcursor just takes the first theme directory
#               it finds under ~/.local/share/icons, which may not be ours.
#
# omarchy-hook-install copies the hook file into
# ~/.config/omarchy/hooks/<type>.d/, it does not symlink it, so the installed
# copy can't find its own plugin directory by relative path once it's been
# moved there. Generate the hook with this plugin's real absolute path baked
# in, rather than shipping a static file that assumes it's still sitting next
# to recolor.py.
set -euo pipefail
PLUGIN_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

tmp=$(mktemp -d)/cursor-accent.sh
trap 'rm -rf "$(dirname "$tmp")"' EXIT
cat > "$tmp" <<EOF
#!/bin/bash
# Generated by install-cursor-hook.sh, with this plugin's actual install
# path baked in (see that script for why). Re-run it after moving the
# plugin, or after \`omarchy plugin update\` if the install path ever changes.
#
# theme-set passes the new theme's name, post-boot passes nothing. The name
# is only used for logging; the colors always come from the staged theme.
exec python3 "$PLUGIN_DIR/recolor.py" "\${1:-\$(omarchy-theme-current 2>/dev/null || echo unknown)}"
EOF

omarchy hook install theme-set "$tmp"
omarchy hook install post-boot "$tmp"
echo "Applying the current theme's colors now..."
"$PLUGIN_DIR/cursor-accent" follow
